In [60]:
import polars as pl

data_2020 = pl.read_csv("../eavs_clc/data/cleaned/2020.csv", schema_overrides = {"fips_code": pl.String, "year": pl.String})
data_2022 = pl.read_csv("../eavs_clc/data/cleaned/2022.csv", schema_overrides = {"fips_code": pl.String, "year": pl.String})

In [61]:
data_2020 = data_2020.with_columns(
    year = pl.lit(2020)
)

data_2022 = data_2022.with_columns(
    year = pl.lit(2022)
)

In [62]:
combined = data_2020.vstack(data_2022)

In [63]:
combined = combined.fill_null(strategy = "zero")

In [64]:
combined_state = combined.group_by("state")
float_cols = [col for col, dtype in zip(combined.columns, combined.dtypes) 
              if dtype in [pl.Float32, pl.Float64, pl.Int32, pl.Int64]]
string_cols = [col for col, dtype in zip(combined.columns, combined.dtypes) 
              if dtype in [pl.String] and col != "state"]
combined_state = combined_state.agg(
    [pl.col(col).first() for col in string_cols] + 
    [pl.col(col).mean() for col in float_cols]
)

combined_county = combined.group_by("fips_code")
float_cols = [col for col, dtype in zip(combined.columns, combined.dtypes) 
              if dtype in [pl.Float32, pl.Float64, pl.Int32, pl.Int64]]
string_cols = [col for col, dtype in zip(combined.columns, combined.dtypes) 
              if dtype in [pl.String] and col != "fips_code"]
combined_county = combined_county.agg(
    [pl.col(col).first() for col in string_cols] + 
    [pl.col(col).mean() for col in float_cols]

)

In [65]:
combined_state

shape: (56, 57)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬────────┐
│ state      ┆ fips_code  ┆ jurisdict ┆ state_abb ┆ … ┆ voters_re ┆ voters_re ┆ voters_re ┆ year   │
│ ---        ┆ ---        ┆ ion_name  ┆ r         ┆   ┆ moved_tot ┆ moved_fel ┆ moved_non ┆ ---    │
│ str        ┆ str        ┆ ---       ┆ ---       ┆   ┆ al_2020_2 ┆ ony       ┆ response  ┆ f64    │
│            ┆            ┆ str       ┆ str       ┆   ┆ 022       ┆ ---       ┆ ---       ┆        │
│            ┆            ┆           ┆           ┆   ┆ ---       ┆ f64       ┆ f64       ┆        │
│            ┆            ┆           ┆           ┆   ┆ f64       ┆           ┆           ┆        │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪════════╡
│ NORTH      ┆ 3700100000 ┆ ALAMANCE  ┆ NC        ┆ … ┆ 11325.33  ┆ 154.33    ┆ 4913.075  ┆ 2021.0 │
│ CAROLINA   ┆            ┆ COUNTY    ┆           ┆   ┆           ┆           ┆           ┆        │
│ MAINE      ┆ 23         ┆ MAINE -   ┆ ME        ┆ … ┆ 277.35110 ┆ 0.0       ┆ 3.358149  ┆ 2021.0 │
│            ┆            ┆ UOCAVA    ┆           ┆   ┆ 7         ┆           ┆           ┆        │
│ GUAM       ┆ 6600000000 ┆ GUAM      ┆ GU        ┆ … ┆ 9341.5    ┆ 0.0       ┆ 8961.0    ┆ 2021.0 │
│ MISSOURI   ┆ 2900100000 ┆ ADAIR     ┆ MO        ┆ … ┆ 3795.7068 ┆ 107.76293 ┆ 1391.3189 ┆ 2021.0 │
│            ┆            ┆ COUNTY    ┆           ┆   ┆ 97        ┆ 1         ┆ 66        ┆        │
│ OKLAHOMA   ┆ 4000100000 ┆ ADAIR     ┆ OK        ┆ … ┆ 3186.4025 ┆ 41.545455 ┆ 1293.8831 ┆ 2021.0 │
│            ┆            ┆ COUNTY    ┆           ┆   ┆ 97        ┆           ┆ 17        ┆        │
│ …          ┆ …          ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …      │
│ NEW YORK   ┆ 3600100000 ┆ ALBANY    ┆ NY        ┆ … ┆ 7835.2177 ┆ 58.975806 ┆ 838.87096 ┆ 2021.0 │
│            ┆            ┆ COUNTY    ┆           ┆   ┆ 42        ┆           ┆ 8         ┆        │
│ ALASKA     ┆ 0200000000 ┆ ALASKA    ┆ AK        ┆ … ┆ 49917.5   ┆ 1645.5    ┆ 26647.5   ┆ 2021.0 │
│ MINNESOTA  ┆ 2700100000 ┆ AITKIN    ┆ MN        ┆ … ┆ 3039.2528 ┆ 0.0       ┆ 1034.2988 ┆ 2021.0 │
│            ┆            ┆ COUNTY    ┆           ┆   ┆ 74        ┆           ┆ 51        ┆        │
│ WYOMING    ┆ 5600100000 ┆ ALBANY    ┆ WY        ┆ … ┆ 1498.2173 ┆ 2.391304  ┆ 1244.6304 ┆ 2021.0 │
│            ┆            ┆ COUNTY    ┆           ┆   ┆ 91        ┆           ┆ 35        ┆        │
│ SOUTH      ┆ 4600300000 ┆ AURORA    ┆ SD        ┆ … ┆ 369.0     ┆ 24.780303 ┆ 157.14393 ┆ 2021.0 │
│ DAKOTA     ┆            ┆ COUNTY    ┆           ┆   ┆           ┆           ┆ 9         ┆        │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴────────┘

In [66]:
combined_county = combined_county.with_columns(
    (pl.when(pl.col("fips_code").str.len_chars() == 9)
    .then(pl.col("fips_code").str.zfill(10))
    .otherwise(pl.col("fips_code")))
    .alias("fips_code")
)

In [67]:
combined_county

shape: (6_460, 57)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬────────┐
│ fips_code  ┆ jurisdicti ┆ state     ┆ state_abb ┆ … ┆ voters_re ┆ voters_re ┆ voters_re ┆ year   │
│ ---        ┆ on_name    ┆ ---       ┆ r         ┆   ┆ moved_tot ┆ moved_fel ┆ moved_non ┆ ---    │
│ str        ┆ ---        ┆ str       ┆ ---       ┆   ┆ al_2020_2 ┆ ony       ┆ response  ┆ f64    │
│            ┆ str        ┆           ┆ str       ┆   ┆ 022       ┆ ---       ┆ ---       ┆        │
│            ┆            ┆           ┆           ┆   ┆ ---       ┆ f64       ┆ f64       ┆        │
│            ┆            ┆           ┆           ┆   ┆ f64       ┆           ┆           ┆        │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪════════╡
│ 2706500000 ┆ KANABEC    ┆ MINNESOTA ┆ MN        ┆ … ┆ 744.0     ┆ 0.0       ┆ 339.5     ┆ 2021.0 │
│            ┆ COUNTY     ┆           ┆           ┆   ┆           ┆           ┆           ┆        │
│ 3903900000 ┆ DEFIANCE   ┆ OHIO      ┆ OH        ┆ … ┆ 2931.5    ┆ 61.0      ┆ 887.0     ┆ 2021.0 │
│            ┆ COUNTY     ┆           ┆           ┆   ┆           ┆           ┆           ┆        │
│ 5184000000 ┆ WINCHESTER ┆ VIRGINIA  ┆ VA        ┆ … ┆ 3518.0    ┆ 50.5      ┆ 541.5     ┆ 2021.0 │
│            ┆ CITY       ┆           ┆           ┆   ┆           ┆           ┆           ┆        │
│ 44825      ┆ TOWN OF    ┆ WISCONSIN ┆ WI        ┆ … ┆ 52.5      ┆ 0.0       ┆ 16.0      ┆ 2021.0 │
│            ┆ LISBON -   ┆           ┆           ┆   ┆           ┆           ┆           ┆        │
│            ┆ JUNEAU     ┆           ┆           ┆   ┆           ┆           ┆           ┆        │
│            ┆ COUNTY     ┆           ┆           ┆   ┆           ┆           ┆           ┆        │
│ 81300      ┆ TOWN OF    ┆ WISCONSIN ┆ WI        ┆ … ┆ 23.0      ┆ 0.0       ┆ 4.0       ┆ 2021.0 │
│            ┆ TWO CREEKS ┆           ┆           ┆   ┆           ┆           ┆           ┆        │
│            ┆ -          ┆           ┆           ┆   ┆           ┆           ┆           ┆        │
│            ┆ MANITOWOC… ┆           ┆           ┆   ┆           ┆           ┆           ┆        │
│ …          ┆ …          ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …      │
│ 5303300000 ┆ KING       ┆ WASHINGTO ┆ WA        ┆ … ┆ 89021.5   ┆ 394.5     ┆ 26607.5   ┆ 2021.0 │
│            ┆ COUNTY     ┆ N         ┆           ┆   ┆           ┆           ┆           ┆        │
│ 3001900000 ┆ DANIELS    ┆ MONTANA   ┆ MT        ┆ … ┆ 112.5     ┆ 0.5       ┆ 44.5      ┆ 2021.0 │
│            ┆ COUNTY     ┆           ┆           ┆   ┆           ┆           ┆           ┆        │
│ 13750      ┆ TOWN OF    ┆ WISCONSIN ┆ WI        ┆ … ┆ 30.0      ┆ 0.0       ┆ 13.0      ┆ 2021.0 │
│            ┆ CENTERVILL ┆           ┆           ┆   ┆           ┆           ┆           ┆        │
│            ┆ E -        ┆           ┆           ┆   ┆           ┆           ┆           ┆        │
│            ┆ MANITOWO…  ┆           ┆           ┆   ┆           ┆           ┆           ┆        │
│ 78075      ┆ TOWN OF    ┆ WISCONSIN ┆ WI        ┆ … ┆ 131.5     ┆ 1.0       ┆ 34.0      ┆ 2021.0 │
│            ┆ SUGAR CAMP ┆           ┆           ┆   ┆           ┆           ┆           ┆        │
│            ┆ - ONEIDA   ┆           ┆           ┆   ┆           ┆           ┆           ┆        │
│            ┆ CO…        ┆           ┆           ┆   ┆           ┆           ┆           ┆        │
│ 2500119295 ┆ EASTHAM    ┆ MASSACHUS ┆ MA        ┆ … ┆ 620.5     ┆ 0.0       ┆ 36.5      ┆ 2021.0 │
│            ┆ TOWN       ┆ ETTS      ┆           ┆   ┆           ┆           ┆           ┆        │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴────────┘

In [68]:
column_list = [
    'total_registrations_received',
    'new_valid_registrations',
    'rejected_registrations',
    'total_forms_mail_fax_email',
    'new_registrations_mail_fax_email',
    'rejected_registrations_mail_fax_email',
    'total_forms_in_person',
    'new_registrations_in_person',
    'rejected_registrations_in_person',
    'total_forms_online',
    'new_registrations_online',
    'rejected_registrations_online',
    'total_forms_dmv',
    'new_registrations_dmv',
    'rejected_registrations_dmv',
    'total_forms_mandatory_nvra',
    'new_registrations_mandatory_nvra',
    'rejected_registrations_mandatory_nvra',
    'total_forms_disability_agency',
    'new_registrations_disability_agency',
    'rejected_registrations_disability_agency',
    'total_forms_armed_forces',
    'new_registrations_armed_forces',
    'rejected_registrations_armed_forces',
    'total_forms_discretionary_nvra',
    'new_registrations_discretionary_nvra',
    'rejected_registrations_discretionary_nvra',
    'total_forms_advocacy_groups',
    'new_registrations_advocacy_groups',
    'rejected_registrations_advocacy_groups',
    'year'              
]               

combined_state = combined_state.select('state', *column_list)
combined_county = combined_county.select("fips_code", "jurisdiction_name", *column_list)

In [69]:
dataset_list = [combined_state, combined_county]

In [70]:
for name, df in [("state", combined_state), ("county", combined_county)]:
    df = df.with_columns([
        (pl.col("rejected_registrations") / pl.col("total_registrations_received") * 100)
            .alias("percent_rejected_registrations_total"),
        (pl.col("rejected_registrations_mail_fax_email") / pl.col("new_registrations_mail_fax_email") * 100)
            .alias("percent_rejected_registrations_mail_fax_email"),
        (pl.col("rejected_registrations_in_person") / pl.col("new_registrations_in_person") * 100)
            .alias("percent_rejected_registrations_in_person"),
        (pl.col("rejected_registrations_online") / pl.col("new_registrations_online") * 100)
            .alias("percent_rejected_registrations_online"),
        (pl.col("rejected_registrations_dmv") / pl.col("new_registrations_dmv") * 100)
            .alias("percent_rejected_registrations_dmv"),
        (pl.col("rejected_registrations_mandatory_nvra") / pl.col("new_registrations_mandatory_nvra") * 100)
            .alias("percent_rejected_registrations_mandatory_nvra"),
        (pl.col("rejected_registrations_disability_agency") / pl.col("new_registrations_disability_agency") * 100)
            .alias("percent_rejected_registrations_disability_agency"),
        (pl.col("rejected_registrations_armed_forces") / pl.col("new_registrations_armed_forces") * 100)
            .alias("percent_rejected_registrations_armed_forces"),
        (pl.col("rejected_registrations_discretionary_nvra") / pl.col("new_registrations_discretionary_nvra") * 100)
            .alias("percent_rejected_registrations_discretionary_nvra"),
        (pl.col("rejected_registrations_advocacy_groups") / pl.col("new_registrations_advocacy_groups") * 100)
            .alias("percent_rejected_registrations_advocacy_groups"),
    ])

    if name == "state":
        combined_state = df
    else:
        combined_county = df

In [71]:
combined_state = combined_state.with_columns(
    pl.col("percent_rejected_registrations_total")
      .rank(descending=True, method="ordinal")
      .alias("rejected_state_rank")
)

combined_county = combined_county.with_columns(
    pl.col("percent_rejected_registrations_total")
      .rank(descending=True, method="ordinal")
      .alias("rejected_state_rank")
)

In [72]:
combined_state = combined_state.fill_nan(0)

combined_county = combined_county.fill_nan(0)

In [73]:
combined_state

shape: (56, 43)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ state     ┆ total_reg ┆ new_valid ┆ rejected_ ┆ … ┆ percent_r ┆ percent_r ┆ percent_r ┆ rejected │
│ ---       ┆ istration ┆ _registra ┆ registrat ┆   ┆ ejected_r ┆ ejected_r ┆ ejected_r ┆ _state_r │
│ str       ┆ s_receive ┆ tions     ┆ ions      ┆   ┆ egistrati ┆ egistrati ┆ egistrati ┆ ank      │
│           ┆ d         ┆ ---       ┆ ---       ┆   ┆ ons…      ┆ ons…      ┆ ons…      ┆ ---      │
│           ┆ ---       ┆ f64       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ u32      │
│           ┆ f64       ┆           ┆           ┆   ┆ f64       ┆ f64       ┆ f64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ NORTH     ┆ 39850.94  ┆ 12923.16  ┆ 1589.09   ┆ … ┆ 0.0       ┆ 45.771144 ┆ 22.953491 ┆ 9        │
│ CAROLINA  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ MAINE     ┆ 526.09657 ┆ 158.42152 ┆ 0.6167    ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 36       │
│           ┆ 9         ┆ 9         ┆           ┆   ┆           ┆           ┆           ┆          │
│ GUAM      ┆ 8188.0    ┆ 11292.5   ┆ 279.0     ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 11       │
│ MISSOURI  ┆ 4854.6034 ┆ 4854.6034 ┆ 0.159483  ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 48       │
│           ┆ 48        ┆ 48        ┆           ┆   ┆           ┆           ┆           ┆          │
│ OKLAHOMA  ┆ 8317.8896 ┆ 4318.2337 ┆ 175.20129 ┆ … ┆ 0.0       ┆ 16.981132 ┆ 0.0       ┆ 16       │
│           ┆ 1         ┆ 66        ┆ 9         ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ NEW YORK  ┆ 32649.580 ┆ 12297.580 ┆ 1386.5483 ┆ … ┆ 0.0       ┆ 6.374867  ┆ 4.224717  ┆ 8        │
│           ┆ 645       ┆ 645       ┆ 87        ┆   ┆           ┆           ┆           ┆          │
│ ALASKA    ┆ 1053947.5 ┆ 57304.0   ┆ 9240.0    ┆ … ┆ 13.879004 ┆ 15.909091 ┆ 0.0       ┆ 25       │
│ MINNESOTA ┆ 15660.902 ┆ 4579.6264 ┆ 4.293103  ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.032625  ┆ 43       │
│           ┆ 299       ┆ 37        ┆           ┆   ┆           ┆           ┆           ┆          │
│ WYOMING   ┆ 3484.0217 ┆ 1400.5217 ┆ 3.913043  ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 37       │
│           ┆ 39        ┆ 39        ┆           ┆   ┆           ┆           ┆           ┆          │
│ SOUTH     ┆ 2359.3181 ┆ 898.39393 ┆ 0.340909  ┆ … ┆ 0.0       ┆ 0.204082  ┆ 0.049801  ┆ 46       │
│ DAKOTA    ┆ 82        ┆ 9         ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [74]:
combined_pie_chart = combined_state.melt(
    id_vars=["state"],
    value_vars=[
        "rejected_registrations_advocacy_groups",
        "rejected_registrations_armed_forces",
        "rejected_registrations_disability_agency",
        "rejected_registrations_discretionary_nvra",
        "rejected_registrations_dmv",
        "rejected_registrations_in_person",
        "rejected_registrations_mail_fax_email",
        "rejected_registrations_mandatory_nvra",
        "rejected_registrations_online",
    ],
    variable_name="rejection_type",
    value_name="count"
)

name_map = {
    "rejected_registrations_advocacy_groups": "Advocacy Groups",
    "rejected_registrations_armed_forces": "Armed Forces",
    "rejected_registrations_disability_agency": "Disability Agency",
    "rejected_registrations_discretionary_nvra": "Discretionary NVRA",
    "rejected_registrations_dmv": "DMV",
    "rejected_registrations_in_person": "In Person",
    "rejected_registrations_mail_fax_email": "Mail/Fax/Email",
    "rejected_registrations_mandatory_nvra": "Mandatory NVRA",
    "rejected_registrations_online": "Online",
}

combined_pie_chart = combined_pie_chart.with_columns(
    pl.col("rejection_type").map_elements(lambda x: name_map.get(x, x)).alias("rejection_type")
)

C:\Users\andre\AppData\Local\Temp\ipykernel_2200\2748972747.py:1: DeprecationWarning: `DataFrame.melt` is deprecated. Use `unpivot` instead, with `index` instead of `id_vars` and `on` instead of `value_vars`
  combined_pie_chart = combined_state.melt(
C:\Users\andre\AppData\Local\Temp\ipykernel_2200\2748972747.py:30: MapWithoutReturnDtypeWarning: Calling `map_elements` without specifying `return_dtype` can lead to unpredictable results. Specify `return_dtype` to silence this warning.
  combined_pie_chart = combined_pie_chart.with_columns(

In [75]:
combined_pie_chart

shape: (504, 3)
┌────────────────┬─────────────────┬──────────┐
│ state          ┆ rejection_type  ┆ count    │
│ ---            ┆ ---             ┆ ---      │
│ str            ┆ str             ┆ f64      │
╞════════════════╪═════════════════╪══════════╡
│ NORTH CAROLINA ┆ Advocacy Groups ┆ 164.075  │
│ MAINE          ┆ Advocacy Groups ┆ 0.0      │
│ GUAM           ┆ Advocacy Groups ┆ 0.0      │
│ MISSOURI       ┆ Advocacy Groups ┆ 0.0      │
│ OKLAHOMA       ┆ Advocacy Groups ┆ 0.0      │
│ …              ┆ …               ┆ …        │
│ NEW YORK       ┆ Online          ┆ 0.0      │
│ ALASKA         ┆ Online          ┆ 1380.5   │
│ MINNESOTA      ┆ Online          ┆ 0.143678 │
│ WYOMING        ┆ Online          ┆ 0.0      │
│ SOUTH DAKOTA   ┆ Online          ┆ 0.0      │
└────────────────┴─────────────────┴──────────┘

In [76]:
combined_pie_chart_county = combined_county.melt(
    id_vars=["fips_code"],
    value_vars=[
        "rejected_registrations_advocacy_groups",
        "rejected_registrations_armed_forces",
        "rejected_registrations_disability_agency",
        "rejected_registrations_discretionary_nvra",
        "rejected_registrations_dmv",
        "rejected_registrations_in_person",
        "rejected_registrations_mail_fax_email",
        "rejected_registrations_mandatory_nvra",
        "rejected_registrations_online",
    ],
    variable_name="rejection_type",
    value_name="count"
)

name_map = {
    "rejected_registrations_advocacy_groups": "Advocacy Groups",
    "rejected_registrations_armed_forces": "Armed Forces",
    "rejected_registrations_disability_agency": "Disability Agency",
    "rejected_registrations_discretionary_nvra": "Discretionary NVRA",
    "rejected_registrations_dmv": "DMV",
    "rejected_registrations_in_person": "In Person",
    "rejected_registrations_mail_fax_email": "Mail/Fax/Email",
    "rejected_registrations_mandatory_nvra": "Mandatory NVRA",
    "rejected_registrations_online": "Online",
}

combined_pie_chart_county = combined_pie_chart_county.with_columns(
    pl.col("rejection_type").map_elements(lambda x: name_map.get(x, x)).alias("rejection_type")
)

C:\Users\andre\AppData\Local\Temp\ipykernel_2200\1861953229.py:1: DeprecationWarning: `DataFrame.melt` is deprecated. Use `unpivot` instead, with `index` instead of `id_vars` and `on` instead of `value_vars`
  combined_pie_chart_county = combined_county.melt(
C:\Users\andre\AppData\Local\Temp\ipykernel_2200\1861953229.py:30: MapWithoutReturnDtypeWarning: Calling `map_elements` without specifying `return_dtype` can lead to unpredictable results. Specify `return_dtype` to silence this warning.
  combined_pie_chart_county = combined_pie_chart_county.with_columns(

In [77]:
print(f"Total County Fields: {combined_pie_chart_county.select(pl.len()).item():,}")
print(f"Non-Null County Fields: {combined_pie_chart_county.filter(pl.col("count") != 0).select(pl.len()).item():,}")

Total County Fields: 58,140
Non-Null County Fields: 10,302

In [78]:
data_2020.write_csv("2020.csv")
data_2022.write_csv("2022.csv")
combined.write_csv("combined.csv")
combined_county.write_csv("combined_county.csv")
combined_state.write_csv("combined_state.csv")
combined_pie_chart.write_csv("combined_pie_chart.csv")
combined_pie_chart_county.write_csv("combined_pie_chart_county.csv")