In [19]:
import polars as pl

In [20]:
demographic_data = pl.read_csv("cc-est2024-alldata.csv", encoding = "latin-1", schema_overrides = {
    "STATE": pl.String,
    "COUNTY": pl.String,
    "SUMLEV": pl.String,
    "AGEGRP": pl.String
})

demographic_data = demographic_data.with_columns(
    (pl.col("STATE") + pl.col("COUNTY")).alias("FIPS_CODE")
)

print(f"Total Rows: {demographic_data.select(pl.len()).item():,}")

Total Rows: 358,416

In [21]:
agegrp_map = {
    0: "Total",
    1: "Age 0 to 4 years",
    2: "Age 5 to 9 years",
    3: "Age 10 to 14 years",
    4: "Age 15 to 19 years",
    5: "Age 20 to 24 years",
    6: "Age 25 to 29 years",
    7: "Age 30 to 34 years",
    8: "Age 35 to 39 years",
    9: "Age 40 to 44 years",
    10: "Age 45 to 49 years",
    11: "Age 50 to 54 years",
    12: "Age 55 to 59 years",
    13: "Age 60 to 64 years",
    14: "Age 65 to 69 years",
    15: "Age 70 to 74 years",
    16: "Age 75 to 79 years",
    17: "Age 80 to 84 years",
    18: "Age 85 years or older"
}

# Map AGEGRP to labels
demographic_data = demographic_data.with_columns(
    pl.col("AGEGRP").replace(agegrp_map).alias("AGEGRP")
)

In [27]:
demographic_data_agg = (
    demographic_data
    .group_by(["FIPS_CODE", "AGEGRP"])
)

float_cols = [col for col, dtype in zip(demographic_data.columns, demographic_data.dtypes) if dtype in [pl.Float32, pl.Float64, pl.Int32, pl.Int64] and col != "YEAR"]


demographic_data_agg = demographic_data_agg.agg(
    [pl.col(col).first() for col, dtype in zip(demographic_data.columns, demographic_data.dtypes) if dtype == pl.Utf8 and col not in ["FIPS_CODE", "AGEGRP"]] + 
    [pl.col(col).mean() for col in float_cols]

)

demographic_data_agg.head(1)

shape: (1, 80)
┌───────────┬─────────────┬────────┬───────┬───┬───────────┬─────────────┬───────────┬─────────────┐
│ FIPS_CODE ┆ AGEGRP      ┆ SUMLEV ┆ STATE ┆ … ┆ HAAC_MALE ┆ HAAC_FEMALE ┆ HNAC_MALE ┆ HNAC_FEMALE │
│ ---       ┆ ---         ┆ ---    ┆ ---   ┆   ┆ ---       ┆ ---         ┆ ---       ┆ ---         │
│ str       ┆ str         ┆ str    ┆ str   ┆   ┆ f64       ┆ f64         ┆ f64       ┆ f64         │
╞═══════════╪═════════════╪════════╪═══════╪═══╪═══════════╪═════════════╪═══════════╪═════════════╡
│ 05097     ┆ Age 55 to   ┆ 050    ┆ 05    ┆ … ┆ 0.166667  ┆ 0.0         ┆ 0.166667  ┆ 0.166667    │
│           ┆ 59 years    ┆        ┆       ┆   ┆           ┆             ┆           ┆             │
└───────────┴─────────────┴────────┴───────┴───┴───────────┴─────────────┴───────────┴─────────────┘

In [29]:
cols_not_include = [
    "SUMLEV",
    "STATE",
    "COUNTY",
    "STNAME",
    "CTYNAME"
]

eavs_data = pl.read_csv("combined_county.csv", schema_overrides = {"fips_code": pl.String})

eavs_data.filter(pl.col("jurisdiction_name") == "RUSK COUNTY")

shape: (1, 44)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ fips_code ┆ jurisdict ┆ total_reg ┆ new_valid ┆ … ┆ percent_r ┆ percent_r ┆ percent_r ┆ rejected │
│ ---       ┆ ion_name  ┆ istration ┆ _registra ┆   ┆ ejected_r ┆ ejected_r ┆ ejected_r ┆ _state_r │
│ str       ┆ ---       ┆ s_receive ┆ tions     ┆   ┆ egistrati ┆ egistrati ┆ egistrati ┆ ank      │
│           ┆ str       ┆ d         ┆ ---       ┆   ┆ ons…      ┆ ons…      ┆ ons…      ┆ ---      │
│           ┆           ┆ ---       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ i64      │
│           ┆           ┆ f64       ┆           ┆   ┆ f64       ┆ f64       ┆ f64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 484010000 ┆ RUSK      ┆ 8934.5    ┆ 5292.0    ┆ … ┆ 0.0       ┆ 1.442308  ┆ 0.0       ┆ 2171     │
│ 0         ┆ COUNTY    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘